- name: install wget, htop, cockpit, vim
  hosts: all
  tasks:
      
    - name: install extra packages for enterprise linux (epel)
      yum: 
        state: present
        name:
          - epel-release
          
    - name: create vim repo      
      yum_repository:
        name: vim
        description: vim repo
        baseurl: http://mirror.ghettoforge.org/distributions/gf/gf-release-latest.gf.el7.noarch.rpm 
        gpgcheck: yes
        enabled: yes
        gpgkey: http://mirror.ghettoforge.org/distributions/gf/RPM-GPG-KEY-gf.el7
    
    - name: install vim enhanced
      yum:
        state: present
        name:
          - vim-enhanced
          
    - name: install wget, htop
      yum:
        state: present
        name:
          - wget
          - htop
          
    - name: install cockpit and additional packages
      yum:
        state: present
        name:
          - cockpit
          - cockpit-networkmanager
          - cockpit-dashboard
          - cockpit-storaged
          - cockpit-packagekit
          - cockpit-docker
          - cockpit-kubernetes
          - cockpit-machines
          - cockpit-sosreport
          - cockpit-selinux
          - cockpit-kdump
          - cockpit-subscriptions
          - cockpit-machines-ovirt
          - cockpit-pcp
          
    - name: start cockpit
      service:
        name: cockpit
        state: started
        enabled: yes
        
    - name: configure firewall
      firewalld:
        service: cockpit
        permanent: yes
        state: enabled
        immediate: yes
