# Add Graylog Repository
- name: create gpgkey for graylog from template
  template:
    src: gpgkey.j2
    dest: /etc/pki/rpm-gpg/RPM-GPG-KEY-graylog
    owner: root
    group: root
    mode: '0644'

- name: Add Graylog repo
  yum_repository:
    name: graylog
    description: graylog repo
    baseurl: https://packages.graylog2.org/repo/el/stable/3.0/$basearch/
    gpgcheck: 1
    repo_gpgcheck: 0
    gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-graylog
    
# Install Graylog
- name: Install Graylog
  yum:
    state: present
    name:
      - graylog-server
  
# SELinux port add
- name: Set SELinux boolean for Graylog
  seboolean:
    name: httpd_can_network_connect
    state: yes
    persistent: yes
    
# Update the graylog config file #1
- name: Update the graylog config file
  lineinfile:
   path: /etc/graylog/server/server.conf
   regexp: 'password_secret'
   line: 'password_secret = iBZf7SpYjIlyx7BuiEnNlv1uHiDlIUTJUSdZVxibPNIDILCMvuUhD4G42K7H6lJsIDIjbNdcGUtR7afEb7fEmZ9hDopISA1y'
   
# Update the graylog config file #2
- name: Update the graylog config file
  lineinfile:
   path: /etc/graylog/server/server.conf
   regexp: 'root_password_sha2'
   line: 'root_password_sha2 = 2c1c52cdb73d24caf779a65b958981b70dfd3bf7288a9ba5c467f38d50e8123f'
   
# Update the graylog config file #3
- name: Update the graylog config file
  lineinfile:
   path: /etc/graylog/server/server.conf
   regexp: '#http_bind_address = 127.0.0.1:9000'
   line: 'http_bind_address = {{ graylog_ip }}:9000'
   
- name: open firewall port 9000
  firewalld:
    port: 9000/tcp
    permanent: true
    state: enabled
    immediate: yes

# Start Graylog service
- name: Start graylog service
  service:
    name: graylog-server.service
    enabled: yes
    state: restarted

- name: firewalld reload
  command: firewall-cmd --reload
