# Installing Elasticsearch
    
# Install Elasticsearch
- name: Install Elasticsearch
  yum:
    state: latest
    name:
      - elasticsearch
      
# Update Elasticsearch config file to only allow localhost connections
- name: Updating the config file to restrict outside access
  lineinfile:
    path: /etc/elasticsearch/elasticsearch.yml
    regexp: 'network.host:'
    line: 'network.host: {{ elk_ip }}'

# Open firewall port 9200/tcp
- name: open port 9200/tcp
  firewalld:
    port: 9200/tcp
    permanent: yes
    immediate: yes
    state: enabled

# Enable Elasticsearch
- name: Enable Elasticsearch
  service:
    name: elasticsearch
    enabled: yes

# Restart Elasticsearch
- name: Restarting Elasticsearch
  service:
    name: elasticsearch
    state: restarted
