# tasks file for phpmyadmin
- name: install phpmyadmin
  yum:
    state: present
    enablerepo: remi-php73
    name: phpmyadmin
 
- name: update phpMyAdmin.conf
  copy:
    src: phpMyAdmin.conf
    dest: /etc/httpd/conf.d/phpMyAdmin.conf
    owner: root
    group: root
    mode: 0644
  notify: restart httpd
