- name: clone phpipam repo      
  git:
    repo: https://github.com/phpipam/phpipam.git
    dest: /var/www/html/
    force: yes

- name: change file and group permissions for /var/www/html
  file:
    path: /var/www/html
    owner: apache
    group: apache
    recurse: yes
    mode: '0755'
    
- name: chmod 0644
  command: find . -type f -exec chmod 0644 {} \;
  args:
    chdir: /var/www/html/

- name: chmod 0755
  command: find . -type d -exec chmod 0755 {} \;
  args:
    chdir: /var/www/html/

- name: Set selinux policy for directories
  sefcontext:
    target: '{{ item.target }}(/.*)?'
    setype: "{{ item.setype }}"
    state: present
  register: filecontext
  with_items:
    - { target: '/var/www/html(/.*)?', setype: 'httpd_sys_content_t' }
    - { target: '/var/www/html/app/admin/import-export/upload(/.*)?', setype: 'httpd_sys_rw_content_t' }
    - { target: '/var/www/html/app/subnets/import-subnet/upload(/.*)?', setype: 'httpd_sys_rw_content_t' }
    - { target: '/var/www/html/css/1.3.1/images/logo(/.*)?', setype: 'httpd_sys_rw_content_t' }         
       
- name: Copy config file
  copy:
    src: /var/www/html/config.dist.php
    dest: /var/www/html/config.php
    remote_src: yes
    
- name: Update config.php file (1 of 3)
  lineinfile:
    path: /var/www/html/config.php
    regexp: |-
      $db['user'] = 'phpipam';
    line: "$db['user'] = '{{ db_username }}';"
    state: present
    
- name: Update config.php file (2 of 3)
  lineinfile:
    path: /var/www/html/config.php
    regexp: |-
      $db['pass'] = 'phpipamadmin';
    line: "$db['pass'] = '{{ db_password }}';"
    state: present
    
- name: Update config.php file (3 of 3)
  lineinfile:
    path: /var/www/html/config.php
    regexp: |-
      $db['name'] = 'phpipam';
    line: "$db['name'] = '{{ db_database }}';"
    state: present

#SElinux policy for icmp checks
- name: Create http_ping file
  blockinfile:
    path: /opt/http_fping.tt
    create: yes
    block: |
      module http_fping 1.0;
      require {
      type httpd_t;
      class capability net_raw;
      class rawip_socket { getopt create setopt write read };
      }
      #============= httpd_t ==============
      allow httpd_t self:capability net_raw;
      allow httpd_t self:rawip_socket { getopt create setopt write read };
    
- name: Create selinux module 
  command: "{{ item }}"
  with_items:
    - checkmodule -M -m -o /opt/http_fping.mod /opt/http_fping.tt
    - semodule_package -o /opt/http_fping.pp -m /opt/http_fping.mod
    - semodule -i /opt/http_fping.pp

- name: Restart apache
  service:
    name: httpd
    state: restarted
