- name: clone phpipam repo      
  git:
    repo: https://github.com/phpipam/phpipam.git
    dest: /var/www/html/
    force: yes

- name: change file and group permissions for /var/www/html
  file:
    path: /var/www/html
    owner: apache
    group: apache
    recurse: yes
    mode: '0755'
    
- name: chmod 0644
  command: find . -type f -exec chmod 0644 {} \;
  args:
    chdir: /var/www/html/

- name: chmod 0755
  command: find . -type d -exec chmod 0755 {} \;
  args:
    chdir: /var/www/html/

- name: Set selinux policy for directories
    sefcontext:
      target: '{{ item.target }}(/.*)?'
      setype: "{{ item.setype }}"
      state: present
    register: filecontext
    with_items:
      - { target: '/var/www/html(/.*)?', setype: 'httpd_sys_content_t' }
      - { target: '/var/www/html/app/admin/import-export/upload(/.*)?', setype: 'httpd_sys_rw_content_t' }
      - { target: '/var/www/html/app/subnets/import-subnet/upload(/.*)?', setype: 'httpd_sys_rw_content_t' }
      - { target: '/var/www/html/css/1.3.1/images/logo(/.*)?', setype: 'httpd_sys_rw_content_t' }         
       
- name: Configure database connection
  copy:
    src: /var/www/html/config.dist.php
    dest: /var/www/html/config.php
    remote_src: yes
