#Handlers file for mariadb-server

- name: restart firewalld
  systemd:
    name: firewalld
    state: restarted

- name: restart nginx
  systemd:
    name: nginx
    state: restarted
    
- name: restart mysql
  systemd:
    name: mariadb
    state: restarted
