- name: install dependencies
  yum:
    state: present
    name:
      - gcc
      - kernel-devel
      - make
      - ncurses-devel

- name: download and unzip libevent
  unarchive:
    src: "{{ libevent_url }}"
    dest: /tmp
    remote_src: yes

- name: install libevent
  command: "{{ item }}"
  args:
    chdir: "/tmp/{{ libevent_dir }}"
  with_items:
    - "./configure --prefix=/usr/local"
    - "make"
    - "make install"

- name: download and unzip tmux
  unarchive:
    src: "{{ tmux_url }}"
    dest: /tmp
    remote_src: yes

- name: install latest release of tmux
  command: "{{ item }}"
  args:
    chdir: "/tmp/{{ tmux_dir }}"
  with_items:
    - "LDFLAGS=\"-L/usr/local/lib -Wl,-rpath=/usr/local/lib\" ./configure --prefix=/usr/local"
    - "make"
    - "make install"
