- name: install dependencies
  yum:
    state: present
    name:
      - gcc
      - kernel-devel
      - make
      - ncurses-devel

- name: download and unzip libevent
  unarchive:
    src: "{{ libevent_url }}"
    dest: /tmp
    remote_src: yes

- name: install libevent
  command: "{{ item }}"
  args:
    chdir: "/tmp/{{ libevent_dir }}"
  with_items:
    - "./configure --prefix=/usr/local"
    - "make"
    - "make install"

- name: download and unzip tmux
  unarchive:
    src: "{{ tmux_url }}"
    dest: /tmp
    remote_src: yes

- name: install latest release of tmux 1 of 2 
  shell: LDFLAGS="-L/usr/local/lib -Wl,-rpath=/usr/local/lib" ./configure --prefix=/usr/local
  args:
    chdir: "/tmp/{{ tmux_dir }}"
  
- name: install latest release of tmux 2 of 2
  command: "{{ item }}"
  args:
    chdir: "/tmp/{{ tmux_dir }}"
  with_items:
    - "make"
    - "make install"

- name: copy tmux customization file
  template:
   src=.tmux.conf.j2
   dest=~/.tmux.conf
   owner=root
   group=root
   mode=0744
