- name: install cockpit and additional packages
  yum:
    state: present
    name:
      - cockpit
      - cockpit-networkmanager
      - cockpit-dashboard
      - cockpit-storaged
      - cockpit-packagekit
      - cockpit-docker
      - cockpit-kubernetes
      - cockpit-machines
      - cockpit-sosreport
      - cockpit-selinux
      - cockpit-kdump
      - cockpit-subscriptions
      - cockpit-machines-ovirt
      - cockpit-pcp
          
- name: start cockpit
  service:
    name: cockpit
    state: started
    enabled: yes
        
- name: configure firewall
  firewalld:
    service: cockpit
    permanent: yes
    state: enabled
    immediate: yes
