- name: install apache
  yum:
    state: present
    name:
      - httpd
      - mod_ssl
      - libsemanage-python
  
- name: enable and start apache
  systemd:
    name: httpd
    state: started
    enabled: true
    
- name: open port 80
  firewalld:
    service: http
    permanent: true
    state: enabled
    immediate: yes
    
- name: open port 443
  firewalld:
    service: https
    permanent: true
    state: enabled
    immediate: yes
    
- name: set SELinux boolean for apache
  seboolean:
    name: httpd_can_network_connect
    state: yes
    persistent: yes
