# Install docker
- name: install docker
  hosts: all
  tasks:

  # Set up the repository
    - name: Install prereqs
      yum:
        state: present
        name:
          - yum-utils
          - device-mapper-persistent-data
          - lvm2
      
  # Add repository
    - name: Add docker repo
      command: yum-config-manager \ --add-repo \ https://download.docker.com/linux/centos/docker-ce.repo
  
  # Install docker
    - name: install docker
      yum:
        state: present
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io

  # Start docker service
    - name: Start docker service
      service:
        name: docker
        state: started

  # Enable docker service
    - name: Enable docker service
      service:
        name: docker
        enabled: yes
