- name: install elk stack 7
  hosts: all
  vars:
    elk_ip: 192.168.1.26
    
  tasks:

      - name: install java
        yum:
          state: present
          name:
            - java-openjdk
            
      - name: add elasticsearch repo
        yum_repository:
          name: elasticsearch
          description: elasticsearch repo
          baseurl: https://artifacts.elastic.co/packages/7.x/yum
          gpgcheck: yes
          enabled: yes
          gpgkey: https://artifacts.elastic.co/GPG-KEY-elasticsearch
          
      - name: install elasticsearch
        yum:
          state: present
          name: elasticsearch
      
      - name: modify /etc/elasticsearch/elasticsearch.yml
        lineinfile:
          path: /etc/elasticsearch/elasticsearch.yml
          regexp: '#network.host: 192.168.0.1'
          line: 'network.host: {{ elk_ip }}'
          state: present
          
      - name: modify /etc/elasticsearch/elasticsearch.yml
        lineinfile:
          path: /etc/elasticsearch/elasticsearch.yml
          regexp: '#discovery.seed_hosts:'
          line: 'discovery.seed_hosts: []'
          state: present
          
      - name: modify /etc/elasticsearch/elasticsearch.yml
        lineinfile:
          path: /etc/elasticsearch/elasticsearch.yml
          regexp: '#cluster.initial_master_nodes:'
          line: 'cluster.initial_master_nodes: [{{elk_ip}}]'
          state: present
        
      - name: modify /etc/elasticsearch/elasticsearch.yml
        lineinfile:
          path: /etc/elasticsearch/elasticsearch.yml
          regexp: '#action.destructive_requires_name: true'
          insertafter: '#action.destructive_requires_name: true'
          line: 'bootstrap.system_call_filter: false'
          state: present
        
      - name: modify /etc/sysconfig/elasticsearch
        lineinfile:
          path: /etc/sysconfig/elasticsearch
          regexp: '#ES_JAVA_OPTS='
          line: 'ES_JAVA_OPTS="-Djna.tmpdir=/var/lib/elasticsearch/tmp"'
          state: present
      
      - name: start and enable elasticsearch
        service:
          name: elasticsearch
          enabled: yes
          state: started
      
      - name: install kibana
        yum:
          state: present
          name: kibana
      
      - name: modify /etc/kibana/kibana.yml
        lineinfile:
          path: /etc/kibana/kibana.yml
          regexp: 'server.host:'
          line: 'server.host: {{ elk_ip }}'
          state: present
      
      - name: modify /etc/kibana/kibana.yml
        lineinfile:
          path: /etc/kibana/kibana.yml
          regexp: '#elasticsearch.hosts:'
          line: 'elasticsearch.hosts: http://{{ elk_ip }}:9200'
          state: present
      
      - name: open firewall port 5601
        firewalld:
          port: 5601/tcp
          permanent: yes
          state: enabled
          immediate: yes
      
      - name: open firewall port 9200
        firewalld:
          port: 9200/tcp
          permanent: yes
          state: enabled
          immediate: yes
      
      - name: start and enable kibana
        service:
          name: kibana
          enabled: yes
          state: started
