- name: install phpmyadmin
  hosts: all
  vars:
    ip_range: 192.168.0.1/24
  tasks:
  
    - name: add repository for php 7.3
      yum:
        state: present
        name: https://rpms.remirepo.net/enterprise/remi-release-7.rpm

    - name: install php packages
      yum:
        state: present
        enablerepo: remi-php73
        name:
          - php
          - php-common
          - php-mcrypt
          - php-cli
          - php-gd
          - php-curl
          - php-mysqlnd
          - phpmyadmin
          
    - name: install apache
      yum:
        state: present
        name:
          - httpd
          - libsemanage-python  
        
    - name: edit conf file for phpmyadmin
      lineinfile:
        path: /etc/httpd/conf.d/phpMyAdmin.conf
        insertafter: 'Require ip 127.0.0.1'
        line: 'Require ip {{ ip_range }}'
    
    - name: edit conf file for phpmyadmin/setup
      lineinfile:
        path: /etc/httpd/conf.d/phpMyAdmin.conf
        insertafter: 'Allow from 127.0.0.1'
        line: 'Allow from {{ ip_range }}'
    
    - name: Enable and start Apache
      systemd:
        name: httpd
        state: started
        enabled: true
    
    - name: Open port 80
      firewalld:
        service: http
        permanent: true
        state: enabled
        immediate: yes
    
    - name: Open port 443
      firewalld:
        service: https
        permanent: true
        state: enabled
        immediate: yes
    
    - name: Set SELinux boolean for Apache
      seboolean:
        name: httpd_can_network_connect
        state: yes
        persistent: yes
