# Create a cluster for nginx

- name: install pacemaker, coronsync and pcs
  hosts: all
  tasks:
  
    - name: install epel
      yum:
        state: present
        name: epel-release
           
    - name: install pacemaker, corosync, pcs
      yum:
        state: present
        name:
          - pacemaker
          - corosync
          - pcs
          
    - name: install nginx
      yum:
        state: present
        name: nginx
    
    - name: start and enable nginx
      service:
        name: nginx
        state: started
        enabled: yes
    
    - name: open port 80
      firewalld:
        port: 80/tcp
        immediate: yes
        permanent: yes
        state: enabled

    - name: start and enable pcs
      service:
        name: pcsd
        enabled: yes
        state: started

    - name: open firewall high availability
      firewalld:
        service: high-availability
        immediate: yes
        state: enabled
        permanent: yes

    - name: create password for hacluster
      user:
        name: hacluster
        update_password: always
        password: "{{ hacluster_pw | password_hash('sha512') }}"

- name: install only on master
  hosts: master
  tasks:

    - name: create cluster
      shell: pcs cluster auth {{ groups.all | join(" ") }} -u hacluster -p {{ hacluster_pw }}
      
    #- name: install expect
    #  yum:
    #    state: present
    #    name: expect
    #
    #- name: create cluster
    #  shell: |
    #    set timeout 300
    #    spawn pcs cluster auth {{ groups.all | join(" ") }}
    #    
    #    expect "Username{{':'}} "
    #    send "hacluster\n"
    #    
    #    expect "\nPassword{{':'}} "
    #    send "{{ hacluster_pw }}\n"
    #    interact
    #    sleep 5
    #    exit 0
    #  args:
    #    executable: /usr/bin/expect
        
    - name: setup cluster
      shell: pcs cluster setup --name {{ hacluster_name}} {{ groups.all | join(" ") }}

    - name: enable cluster
      shell: pcs cluster enable -–all
      
    - name: start cluster
      shell: pcs cluster start -–all

    - name: disable STONITH
      shell: pcs property set stonith-enabled=false

    - name: ignore the quorum policy
      shell: pcs property set no-quorum-policy=ignore
      
    - name: add floating ip address
      shell: pcs resource create v_ip ocf:heartbeat:IPaddr2 ip={{ floating_ip }} cidr_netmask=32 op monitor interval=20s
      
    - name: create nginx hearbeat monitor
      shell: pcs resource create webserver ocf:heartbeat:nginx configfile=/etc/nginx/nginx.conf op monitor timeout="5s" interval="5s"
