# Create a cluster for nginx

- name: install pacemaker, coronsync and pcs
  hosts: all
  tasks:
  
    - name: install epel
      yum:
        state: present
        name: epel-release
           
    - name: install pacemaker, corosync, pcs
      yum:
        state: present
        name:
          - pacemaker
          - corosync
          - pcs
          
    - name: install nginx
      yum:
        state: present
        name: nginx
    
    - name: start and enable nginx
      service:
        name: nginx
        state: started
        enabled: yes
    
    - name: open port 80
      firewalld:
        port: 80/tcp
        immediate: yes
        permanent: yes
        state: enabled
    
    - name: create corosync.conf
      copy:
        src: /etc/corosync/corosync.conf.example
        dest: /etc/corosync/corosync.conf
        remote_src: yes
      
    - name: start and enable pacemaker
      service:
        name: pacemaker
        enabled: yes
        state: started

    - name: start and enable corosync
      service:
        name: corosync
        enabled: yes
        state: started

    - name: start and enable pcs
      service:
        name: pcsd
        enabled: yes
        state: started

    - name: open firewall high availability
      firewalld:
        service: high-availability
        immediate: yes
        state: enabled
        permanent: yes

    - name: create password for hacluster
      user:
        name: hacluster
        update_password: always
        password: "{{ hacluster_pw | password_hash('sha512') }}"

- name: install only on master
  hosts: master
  tasks:

    - name: install expect
      yum:
        state: present
        name: expect
        
    - name: Create kibana admin user
      template:
        src=hacluster.j2
        dest=/tmp/hacluster
        owner=root
        group=root
        mode=0744
    
    - name: create cluster
      shell:
        set timeout 30
        spawn bash /tmp/hacluster
        expect "Username:"
        send "hacluster\n"
        send "{{ hacluster_pw }}\n"
        exit 0
      args:
        executable: /usr/bin/expect

    - name: setup cluster
      shell: pcs cluster setup --name {{ hacluster_name}} {{ groups.all | join(" ") }}

    - name: start cluster
      command: pcs cluster start -–all

    - name: disable STONITH
      command: pcs property set stonith-enabled=false

    - name: ignore the quorum policy
      command: pcs property set no-quorum-policy=ignore
      
    - name: add floating ip address
      command: pcs resource create v_ip ocf:heartbeat:IPaddr2 ip={{ floating_ip }} cidr_netmask=32 op monitor interval=20s
      
    - name: create nginx hearbeat monitor
      command: pcs resource create webserver ocf:heartbeat:nginx configfile=/etc/nginx/nginx.conf op monitor timeout="5s" interval="5s"
