- name: Install pacemaker, coronsync etc... 
  vars:
    floating_ip: 192.168.1.24
    hacluster_pw: test123
    node01: node01
    node02: node02
  hosts: all
  tasks:
  
    - name: install epel
      yum:
        state: present
        name: epel-release
        
    - name: install nginx
      yum:
        state: present
        name: nginx
        
    - name: install pacemaker, corosync, pcsd
      yum:
        state: present
        name:
          - pacemaker
          - corosync
          - pcsd
          
    - name: start and enable pacemaker
      service:
        name: pacemaker
        enabled: yes
        state: started

    - name: start and enable pacemaker
      service:
        name: corosync
        enabled: yes
        state: started
        
    - name: start and enable pacemaker
      service:
        name: pcsd
        enabled: yes
        state: started
        
    - name: open firewall port 80
      firewalld:
        port: 80/tcp
        immediate: yes
        state: enabled
        permanent: yes
    
    - name: open firewall high availability
      firewalld:
        service: high-availability
        immediate: yes
        state: enabled
        permanent: yes

    - name: create password for hacluster
      user:
        name: hacluster
        password: {{ hacluster_pw }}
        
    - name: create cluster
      when: inventory_hostname == {{ node01 }}
      expect: 
        command: pcs cluster auth {{ node01 }} {{ node02 }}
        responses: {{ hacluster_pw }}
        
    - name: setup cluster
      when: inventory_hostname == {{ node01 }}
      
    - name: enable cluster
      when: inventory_hostname == {{ node01 }}
    
    - name: disable STONITH
      when: inventory_hostname == {{ node01 }}
      
    - name: ignore the quorum policy
      when: inventory_hostname == {{ node01 }}
