- name: install pacemaker, coronsync and pcs
  hosts: all
  tasks:
  
    - name: install epel
      yum:
        state: present
        name: epel-release
           
    - name: install pacemaker, corosync, pcs
      yum:
        state: present
        name:
          - pacemaker
          - corosync
          - pcs

    - name: start and enable pacemaker
      service:
        name: pacemaker
        enabled: yes

    - name: start and enable corosync
      service:
        name: corosync
        enabled: yes

    - name: start and enable pcs
      service:
        name: pcsd
        enabled: yes
        state: started

    - name: open firewall high availability
      firewalld:
        service: high-availability
        immediate: yes
        state: enabled
        permanent: yes

    - name: create password for hacluster
      user:
        name: hacluster
        password: "{{ hacluster_pw }}"

- name: install only on master
  hosts: master
  tasks:

    - name: install expect
      yum:
        state: present
        name: expect

    - name: create cluster
      shell:
        pcs cluster auth {{ hosts['ALL'] }}
        expect "Username:"
        send "hacluster\n"

        expect "Password:"
        send "{{ hacluster_pw }}\n"
      args:
        executable: /usr/bin/expect

    - name: setup cluster
      shell: pcs cluster setup --name {{ hacluster_name}} {{ groups['ALL'] }}

    - name: start cluster
      command: pcs cluster start -–all

    - name: disable STONITH
      command: pcs property set stonith-enabled=false

    - name: ignore the quorum policy
      command: pcs property set no-quorum-policy=ignore
