- name: Install pacemaker, coronsync etc... 
  vars:
    floating_ip: 192.168.1.24
    hacluster_name: testcluster
    hacluster_pw: test123
  hosts: all
  tasks:
  
    - name: install epel
      yum:
        state: present
        name: epel-release
        
    - name: install nginx
      yum:
        state: present
        name: nginx
        
    - name: install pacemaker, corosync, pcs
      yum:
        state: present
        name:
          - pacemaker
          - corosync
          - pcs
          
    - name: start and enable pacemaker
      service:
        name: pacemaker
        enabled: yes

    - name: start and enable corosync
      service:
        name: corosync
        enabled: yes
        
    - name: start and enable pcs
      service:
        name: pcsd
        enabled: yes
        state: started
        
    - name: open firewall port 80
      firewalld:
        port: 80/tcp
        immediate: yes
        state: enabled
        permanent: yes
    
    - name: open firewall high availability
      firewalld:
        service: high-availability
        immediate: yes
        state: enabled
        permanent: yes

    - name: create password for hacluster
      user:
        name: hacluster
        password: "{{ hacluster_pw }}"

- name: run on master only 
  hosts: 192.168.1.25
  vars:  
    node01: 192.168.1.25
    node02: 192.168.1.26
    hacluster_pw: test123
    hacluster_name: testcluster
  tasks:
  
    - name: create cluster
      expect: 
        command: pcs cluster auth {{ node01 }} {{ node02 }}
        responses: "{{ hacluster_pw }}"
        
    - name: setup cluster
      command: pcs cluster setup -name {{ hacluster_name}} {{ node01 }} {{ node02 }}
      
    - name: enable cluster
      command: pcs cluster enable –all
      
    - name: start cluster
      command: pcs cluster start –all
    
    - name: disable STONITH
      command: pcs property set stonith-enabled=false
      
    - name: ignore the quorum policy
      command: pcs property set no-quorum-policy=ignore

    - name: add floating ip address
      command: pcs resource create v_ip ocf:heartbeat:IPaddr2 ip={{ floating_ip }} cidr_netmask=32 op monitor interval=20s
