- name: install node exporter for prometheus
  hosts: all
  tasks:
  
    - name: create node_exporter user
      command: useradd -rs /bin/false node_exporter
    
    - name: create node_exporter service
      blockinfile:
        path: /etc/systemd/system/node_exporter.service
        create: yes
        marker: ""
        block: |
          [Unit]
          Description=Node Exporter
          After=network.target
          
          [Service]
          User=node_exporter
          Group=node_exporter
          Type=simple
          ExecStart=/usr/local/bin/node_exporter

          [Install]
          WantedBy=multi-user.target
    
    - firewalld:
        port: 9100/tcp
        permanent: yes
        enabled: yes
    
    - name: daemon reload
      command: systemctl daemon-reload
      
    - name: start and enable node_exporter
      service:
        name: node_exporter
        state: started
        enabled: yes
