- name: Install Apache
  yum:
    state: present
    name:
      - httpd
      - mod_ssl
      - libsemanage-python
  
- name: Enable and start Apache
  systemd:
    name: httpd
    state: started
    enabled: true
    
# Open firewall port 80
- name: open firewall
  firewalld:
    port: 80/tcp
    permanent: yes
    state: enabled
    immediate: yes

# Open firewall port 443
- name: open firewall
  firewalld:
    port: 443/tcp
    permanent: yes
    state: enabled
    immediate: yes
    
- name: Set SELinux boolean for Apache
  seboolean:
    name: httpd_can_network_connect
    state: yes
    persistent: yes
