- name: Add repository for php 7.3
  yum:
    state: present
    name: https://rpms.remirepo.net/enterprise/remi-release-7.rpm

- name: Install php packages
  yum:
    state: present
    enablerepo: remi-php73
    name:
      - php
      - php-common
      - php-cli
      - php-gd
      - php-curl
      - php-mysqlnd
