- name: Install filebeat
  hosts: all
  vars:
    filebeat_module: nginx
    elk_ip: 192.168.1.73
  tasks:
  
    - name: add repository
      yum_repository:
        name: elastic-beats
        description: elastic-beats repo
        baseurl: https://artifacts.elastic.co/packages/oss-6.x/yum
        gpgcheck: 1
        enabled: yes
        gpgkey: https://artifacts.elastic.co/GPG-KEY-elasticsearch

    - name: install filebeat
      yum:
        state: present
        name:
          - filebeat
 
    - name: setup kibana - edit filebeat.yml
      lineinfile:
        path: /etc/filebeat/filebeat.yml
        regexp: '#host: "localhost:5601"'
        line: 'host: "{{ elk_ip }}:5601"'
        
    - name: setup elasticsearch - edit filebeat.yml
      lineinfile:
        path: /etc/filebeat/filebeat.yml
        regexp: 'hosts: \["localhost:9200"\]'
        line: '  hosts: "{{ elk_ip }}:9200"'
    
    - name: setup logstash - edit metricbeat.yml
      lineinfile:
        path: /etc/metricbeat/metricbeat.yml
        regexp: 'hosts: \["localhost:5400"\]'
        line: '  hosts: ["{{ elk_ip }}:5400"]'
    
    - name: enable module(s)
      command: filebeat modules enable {{ filebeat_module }}
      
    - name: run filebeat setup
      command: filebeat setup

    - name: start and enable filebeat
      service:
        name: filebeat
        enabled: yes
        state: started
