- name: install docker and docker-compose centos8
  hosts: all
  tasks:
  
    - name: install pre-requisities
      yum:
        name:
          - epel-release
          - git
          - gcc
          - gcc-c++
          - ansible
          - nodejs
          - gettext
          - device-mapper-persistent-data
          - lvm2
          - bzip2
          - python3-pip
        
