# Mount Zabbix repo
  - name: add zabbix repo
    yum:
      state: present
      name: https://repo.zabbix.com/zabbix/4.2/rhel/7/x86_64/zabbix-release-4.2-1.el7.noarch.rpm
        
# Install Zabbix
  - name: install zabbix with mysql
    yum:
      state: present
      name:
        - zabbix-server-mysql
        - zabbix-web-mysql
        - zabbix-agent
        - zabbix-get
