- name: Add repository for php 7.3
  yum:
    state: present
    name: https://rpms.remirepo.net/enterprise/remi-release-7.rpm

- name: Install php packages
  yum:
    state: present
    name:
      - php73
      - php73-php-common
      - php73-php-opcache
      - php73-php-mcrypt
      - php73-php-cli
      - php73-php-gd
      - php73-php-curl
      - php73-php-mysqlnd
