# Installing Elasticsearch
    
# Install elasticsearch
- name: Install Elasticsearch
  yum:
    state: latest
    name:
      - elasticsearch
      
# Update elasticsearch config file
- name: Allow outside access to elasticsearch
  lineinfile:
    path: /etc/elasticsearch/elasticsearch.yml
    regexp: 'network.host:'
    line: 'network.host: {{ elk_ip }}'
    
- name: Add requirement for elk stack 7
  lineinfile:
    path: /etc/elasticsearch/elasticsearch.yml
    line: 'cluster.initial_master_nodes: ["node-1"]'
   
# Enable and start elasticsearch
- name: Enable Elasticsearch
  service:
    name: elasticsearch
    enabled: yes
    state: started

# Open firewall port 9200/tcp
- name: open port 9200/tcp
  firewalld:
    port: 9200/tcp
    permanent: yes
    immediate: yes
    state: enabled
