# Install Grafana
- name: Install Grafana
  hosts: all
  tasks:
  
    - name: add repository
      yum_repository:
        name: grafana
        description: grafana repo
        baseurl: https://packages.grafana.com/oss/rpm
        gpgcheck: 1
        enabled: yes
        gpgkey: https://packages.grafana.com/gpg.key
    
    - name: install grafana
      yum:
        state: present
        name:
          - grafana
