# Installing Elasticsearch

# Add Elasticsearch repo
- name: Add Elasticsearch repo
  yum_repository:
    name: elasticsearch
    description: elasticsearch repo
    baseurl: https://artifacts.elastic.co/packages/7.x/yum
    gpgkey: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    
# Install Elasticsearch
- name: Install Elasticsearch
  yum:
    state: latest
    name:
      - elasticsearch
      
# Update the graylog config file
- name: Update the graylog config file
  lineinfile:
   path: /etc/elasticsearch/elasticsearch.yml
   regexp: '#cluster.name:'
   line: 'cluster.name: graylog'
   
# Update the graylog config file
- name: Update the graylog config file
  lineinfile:
   path: /etc/elasticsearch/elasticsearch.yml
   insertafter: 'cluster.name: graylog'
   line: 'action.auto_create_index: false'
   state: present   

# Open firewall port 9200/tcp
- name: open port 9200/tcp
  firewalld:
    port: 9200/tcp
    permanent: yes
    state: enabled

# Enable Elasticsearch
- name: Restarting Elasticsearch
  service:
    name: elasticsearch
    enabled: yes

# Restart Elasticsearch
- name: Restarting Elasticsearch
  service:
    name: elasticsearch
    state: restarted
