# Not TESTED

- name: install katello agent
  hosts: all
  vars:
    key: --org="Anura" --activationkey="CentOS7 Base/Epel"
    katello_ip: 192.168.1.8
    katello_hostname: foreman.ezanga.local
    katello_latest_repo: https://yum.theforeman.org/client/1.24/el7/x86_64/foreman-client-release.rpm
    
  tasks:
    
    - name: create directory for backup repo files
      file:
        path: /etc/yum.repos.d/backuprepo
        state: directory
    
    - name: move repos to /etc/yum.repos.d/backuprepo
      shell: mv /etc/yum.repos.d/* /etc/yum.repos.d/backuprepo
    
    - name: edit hosts file
      lineinfile:
        path: /etc/hosts
        line: '{{ katello_ip }} {{ katello_hostname }}'
    
    - name: install subscription-manager
      yum:
        state: present
        name:
          - subscription-manager
          
    - name: download and install ca-consumer package
      yum:
        state: present
        name: http://{{ katello_ip }}/pub/katello-ca-consumer-{{katello_hostname}}-1.0-1.noarch.rpm
        
    - name: register the client with katello
      command: subscription-manager register {{ key }}
    
    - name: install katello repo
      yum:
        state: present
        name: "{{ katello_latest_repo }}"
    
    - name: install katello-host-tools
      yum:
        state: present
        name:
          - katello-host-tools
          
    - name: start and enable katello
      service:
        name: goferd
        enabled: yes
        state: started
